{-# LANGUAGE OverloadedStrings #-}

module Test.HgLib.SummarySpec (spec) where

import Control.Exception (try, SomeException)
import Data.Text (Text)
import HgLib.Types
import System.OsPath (OsPath)
import Test.HgLib.Common
import Test.Hspec
import qualified Data.Text as T
import qualified HgLib.Commands as C
import qualified System.FilePath
import qualified System.OsPath as OsPath

-- Helper function to check if Either is Left
isLeft :: Either a b -> Bool
isLeft (Left _) = True
isLeft (Right _) = False

spec :: Spec
spec = describe "Summary" $ do

-- Conversion notes:
-- WARNING: Unknown client method: summary
-- WARNING: Unknown client method: summary
-- WARNING: Unknown client method: summary
-- WARNING: Unknown client method: summary
-- WARNING: Unknown client method: summary
-- WARNING: Unknown client method: summary
-- WARNING: Unknown client method: summary
-- TODO: Unhandled expression: Dictionary {dict_mappings = [DictMappingPair (Call
-- TODO: Unhandled expression: Dictionary {dict_mappings = [DictMappingPair (Call
-- TODO: Unhandled expression: Dictionary {dict_mappings = [DictMappingPair (Call
-- TODO: Unhandled expression: Dictionary {dict_mappings = [DictMappingPair (Call
-- TODO: Unhandled method call: hglib.open
-- TODO: Unhandled expression: Dictionary {dict_mappings = [DictMappingPair (Call
-- TODO: Unhandled expression: Dictionary {dict_mappings = [DictMappingPair (Call
-- TODO: Unhandled expression: Dictionary {dict_mappings = [DictMappingPair (Call
-- TODO: Unhandled expression: Dictionary {dict_mappings = [DictMappingPair (Call
-- TODO: Unhandled module attribute: self.client.version
-- TODO: Complex assignment pattern: [Subscript {subscriptee = Var {var_ident = Ident {ident_string = "d", ident_annot = SpanPoint {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 24, span_column = 13}}, expr_annot = SpanPoint {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 24, span_column = 13}}, subscript_expr = Call {call_fun = Var {var_ident = Ident {ident_string = "b", ident_annot = SpanPoint {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 24, span_column = 15}}, expr_annot = SpanPoint {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 24, span_column = 15}}, call_args = [ArgExpr {arg_expr = Strings {strings_strings = ["'phases'"], expr_annot = SpanCoLinear {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 24, span_start_column = 17, span_end_column = 24}}, arg_annot = SpanCoLinear {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 24, span_start_column = 17, span_end_column = 24}}], expr_annot = SpanCoLinear {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 24, span_start_column = 15, span_end_column = 25}}, expr_annot = SpanCoLinear {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 24, span_start_column = 13, span_end_column = 26}}]
-- TODO: Unhandled expression: Dictionary {dict_mappings = [DictMappingPair (Call
-- TODO: Unhandled module attribute: self.client.version
-- TODO: Complex assignment pattern: [Subscript {subscriptee = Var {var_ident = Ident {ident_string = "d", ident_annot = SpanPoint {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 38, span_column = 13}}, expr_annot = SpanPoint {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 38, span_column = 13}}, subscript_expr = Call {call_fun = Var {var_ident = Ident {ident_string = "b", ident_annot = SpanPoint {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 38, span_column = 15}}, expr_annot = SpanPoint {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 38, span_column = 15}}, call_args = [ArgExpr {arg_expr = Strings {strings_strings = ["'phases'"], expr_annot = SpanCoLinear {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 38, span_start_column = 17, span_end_column = 24}}, arg_annot = SpanCoLinear {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 38, span_start_column = 17, span_end_column = 24}}], expr_annot = SpanCoLinear {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 38, span_start_column = 15, span_end_column = 25}}, expr_annot = SpanCoLinear {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 38, span_start_column = 13, span_end_column = 26}}]
-- TODO: Unhandled module attribute: self.client.version
-- TODO: Unhandled binary operator: LessThan {op_annot = SpanPoint {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 43, span_column = 32}}
-- TODO: Raise statement conversion
-- TODO: Unhandled binary operator: Modulo {op_annot = SpanPoint {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 47, span_column = 36}}
-- TODO: Unhandled expression: Dictionary {dict_mappings = [DictMappingPair (Call
-- TODO: Unhandled module attribute: self.client.version
-- TODO: Complex assignment pattern: [Subscript {subscriptee = Var {var_ident = Ident {ident_string = "d", ident_annot = SpanPoint {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 63, span_column = 13}}, expr_annot = SpanPoint {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 63, span_column = 13}}, subscript_expr = Call {call_fun = Var {var_ident = Ident {ident_string = "b", ident_annot = SpanPoint {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 63, span_column = 15}}, expr_annot = SpanPoint {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 63, span_column = 15}}, call_args = [ArgExpr {arg_expr = Strings {strings_strings = ["'phases'"], expr_annot = SpanCoLinear {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 63, span_start_column = 17, span_end_column = 24}}, arg_annot = SpanCoLinear {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 63, span_start_column = 17, span_end_column = 24}}], expr_annot = SpanCoLinear {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 63, span_start_column = 15, span_end_column = 25}}, expr_annot = SpanCoLinear {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 63, span_start_column = 13, span_end_column = 26}}]
-- TODO: Unhandled method call: hglib.open
-- TODO: Unhandled expression: Dictionary {dict_mappings = [DictMappingPair (Call
-- TODO: Unhandled method call: other.summary
-- TODO: Complex assignment pattern: [Subscript {subscriptee = Var {var_ident = Ident {ident_string = "d", ident_annot = SpanPoint {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 85, span_column = 9}}, expr_annot = SpanPoint {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 85, span_column = 9}}, subscript_expr = Call {call_fun = Var {var_ident = Ident {ident_string = "b", ident_annot = SpanPoint {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 85, span_column = 11}}, expr_annot = SpanPoint {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 85, span_column = 11}}, call_args = [ArgExpr {arg_expr = Strings {strings_strings = ["'remote'"], expr_annot = SpanCoLinear {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 85, span_start_column = 13, span_end_column = 20}}, arg_annot = SpanCoLinear {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 85, span_start_column = 13, span_end_column = 20}}], expr_annot = SpanCoLinear {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 85, span_start_column = 11, span_end_column = 21}}, expr_annot = SpanCoLinear {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 85, span_start_column = 9, span_end_column = 22}}]
-- TODO: Unhandled method call: other.summary
-- TODO: Complex assignment pattern: [Subscript {subscriptee = Var {var_ident = Ident {ident_string = "d", ident_annot = SpanPoint {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 89, span_column = 9}}, expr_annot = SpanPoint {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 89, span_column = 9}}, subscript_expr = Call {call_fun = Var {var_ident = Ident {ident_string = "b", ident_annot = SpanPoint {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 89, span_column = 11}}, expr_annot = SpanPoint {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 89, span_column = 11}}, call_args = [ArgExpr {arg_expr = Strings {strings_strings = ["'remote'"], expr_annot = SpanCoLinear {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 89, span_start_column = 13, span_end_column = 20}}, arg_annot = SpanCoLinear {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 89, span_start_column = 13, span_end_column = 20}}], expr_annot = SpanCoLinear {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 89, span_start_column = 11, span_end_column = 21}}, expr_annot = SpanCoLinear {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 89, span_start_column = 9, span_end_column = 22}}]
-- TODO: Unhandled method call: other.summary
-- TODO: Unhandled method call: other.bookmark
-- TODO: Complex assignment pattern: [Subscript {subscriptee = Var {var_ident = Ident {ident_string = "d", ident_annot = SpanPoint {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 93, span_column = 9}}, expr_annot = SpanPoint {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 93, span_column = 9}}, subscript_expr = Call {call_fun = Var {var_ident = Ident {ident_string = "b", ident_annot = SpanPoint {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 93, span_column = 11}}, expr_annot = SpanPoint {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 93, span_column = 11}}, call_args = [ArgExpr {arg_expr = Strings {strings_strings = ["'remote'"], expr_annot = SpanCoLinear {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 93, span_start_column = 13, span_end_column = 20}}, arg_annot = SpanCoLinear {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 93, span_start_column = 13, span_end_column = 20}}], expr_annot = SpanCoLinear {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 93, span_start_column = 11, span_end_column = 21}}, expr_annot = SpanCoLinear {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 93, span_start_column = 9, span_end_column = 22}}]
-- TODO: Unhandled module attribute: self.client.version
-- TODO: Unhandled binary operator: LessThan {op_annot = SpanPoint {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 94, span_column = 32}}
-- TODO: Complex assignment pattern: [Subscript {subscriptee = Var {var_ident = Ident {ident_string = "d", ident_annot = SpanPoint {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 95, span_column = 13}}, expr_annot = SpanPoint {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 95, span_column = 13}}, subscript_expr = Call {call_fun = Var {var_ident = Ident {ident_string = "b", ident_annot = SpanPoint {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 95, span_column = 15}}, expr_annot = SpanPoint {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 95, span_column = 15}}, call_args = [ArgExpr {arg_expr = Strings {strings_strings = ["'parent'"], expr_annot = SpanCoLinear {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 95, span_start_column = 17, span_end_column = 24}}, arg_annot = SpanCoLinear {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 95, span_start_column = 17, span_end_column = 24}}], expr_annot = SpanCoLinear {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 95, span_start_column = 15, span_end_column = 25}}, expr_annot = SpanCoLinear {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 95, span_start_column = 13, span_end_column = 26}}]
-- TODO: Complex assignment pattern: [Subscript {subscriptee = Var {var_ident = Ident {ident_string = "d", ident_annot = SpanPoint {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 97, span_column = 13}}, expr_annot = SpanPoint {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 97, span_column = 13}}, subscript_expr = Call {call_fun = Var {var_ident = Ident {ident_string = "b", ident_annot = SpanPoint {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 97, span_column = 15}}, expr_annot = SpanPoint {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 97, span_column = 15}}, call_args = [ArgExpr {arg_expr = Strings {strings_strings = ["'bookmarks'"], expr_annot = SpanCoLinear {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 97, span_start_column = 17, span_end_column = 27}}, arg_annot = SpanCoLinear {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 97, span_start_column = 17, span_end_column = 27}}], expr_annot = SpanCoLinear {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 97, span_start_column = 15, span_end_column = 28}}, expr_annot = SpanCoLinear {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 97, span_start_column = 13, span_end_column = 29}}]
-- TODO: Unhandled method call: other.summary
-- TODO: Unhandled method call: other.commit
-- TODO: Complex assignment pattern: [Subscript {subscriptee = Var {var_ident = Ident {ident_string = "d", ident_annot = SpanPoint {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 103, span_column = 9}}, expr_annot = SpanPoint {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 103, span_column = 9}}, subscript_expr = Call {call_fun = Var {var_ident = Ident {ident_string = "b", ident_annot = SpanPoint {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 103, span_column = 11}}, expr_annot = SpanPoint {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 103, span_column = 11}}, call_args = [ArgExpr {arg_expr = Strings {strings_strings = ["'remote'"], expr_annot = SpanCoLinear {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 103, span_start_column = 13, span_end_column = 20}}, arg_annot = SpanCoLinear {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 103, span_start_column = 13, span_end_column = 20}}], expr_annot = SpanCoLinear {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 103, span_start_column = 11, span_end_column = 21}}, expr_annot = SpanCoLinear {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 103, span_start_column = 9, span_end_column = 22}}]
-- TODO: Unhandled module attribute: self.client.version
-- TODO: Unhandled binary operator: LessThan {op_annot = SpanPoint {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 104, span_column = 32}}
-- TODO: Complex assignment pattern: [Subscript {subscriptee = Var {var_ident = Ident {ident_string = "d", ident_annot = SpanPoint {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 108, span_column = 9}}, expr_annot = SpanPoint {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 108, span_column = 9}}, subscript_expr = Call {call_fun = Var {var_ident = Ident {ident_string = "b", ident_annot = SpanPoint {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 108, span_column = 11}}, expr_annot = SpanPoint {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 108, span_column = 11}}, call_args = [ArgExpr {arg_expr = Strings {strings_strings = ["'parent'"], expr_annot = SpanCoLinear {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 108, span_start_column = 13, span_end_column = 20}}, arg_annot = SpanCoLinear {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 108, span_start_column = 13, span_end_column = 20}}], expr_annot = SpanCoLinear {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 108, span_start_column = 11, span_end_column = 21}}, expr_annot = SpanCoLinear {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 108, span_start_column = 9, span_end_column = 22}}]
-- TODO: Unhandled module attribute: self.client.version
-- TODO: Complex assignment pattern: [Subscript {subscriptee = Var {var_ident = Ident {ident_string = "d", ident_annot = SpanPoint {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 110, span_column = 13}}, expr_annot = SpanPoint {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 110, span_column = 13}}, subscript_expr = Call {call_fun = Var {var_ident = Ident {ident_string = "b", ident_annot = SpanPoint {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 110, span_column = 15}}, expr_annot = SpanPoint {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 110, span_column = 15}}, call_args = [ArgExpr {arg_expr = Strings {strings_strings = ["'phases'"], expr_annot = SpanCoLinear {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 110, span_start_column = 17, span_end_column = 24}}, arg_annot = SpanCoLinear {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 110, span_start_column = 17, span_end_column = 24}}], expr_annot = SpanCoLinear {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 110, span_start_column = 15, span_end_column = 25}}, expr_annot = SpanCoLinear {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 110, span_start_column = 13, span_end_column = 26}}]
-- TODO: Unhandled method call: other.summary
-- TODO: Unhandled expression: Dictionary {dict_mappings = [DictMappingPair (Call
-- TODO: Unhandled module attribute: self.client.version
-- TODO: Complex assignment pattern: [Subscript {subscriptee = Var {var_ident = Ident {ident_string = "d", ident_annot = SpanPoint {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 133, span_column = 13}}, expr_annot = SpanPoint {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 133, span_column = 13}}, subscript_expr = Call {call_fun = Var {var_ident = Ident {ident_string = "b", ident_annot = SpanPoint {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 133, span_column = 15}}, expr_annot = SpanPoint {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 133, span_column = 15}}, call_args = [ArgExpr {arg_expr = Strings {strings_strings = ["'phases'"], expr_annot = SpanCoLinear {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 133, span_start_column = 17, span_end_column = 24}}, arg_annot = SpanCoLinear {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 133, span_start_column = 17, span_end_column = 24}}], expr_annot = SpanCoLinear {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 133, span_start_column = 15, span_end_column = 25}}, expr_annot = SpanCoLinear {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 133, span_start_column = 13, span_end_column = 26}}]

  it "should handle empty repository" $
    withTestRepo $ \bt -> do
      let client = btClient bt
      d <- -- TODO: Dictionary {dict_mappings = [DictMappingPair (Call
      -- TODO: client.summary `shouldBe` -- TODO: Dictionary {dict_mappings = [DictMappingPair (Call

  it "should handle basic repository with one commit" $
    withTestRepo $ \bt -> do
      let client = btClient bt
      commonAppendFile "a" "a"
      (rev, node) <- C.commit client ((mkDefaultCommitOptions "first") { commitAddRemove = True })
      d <- -- TODO: Dictionary {dict_mappings = [DictMappingPair (Call
      when (-- TODO: self.client.version == (3, 5)) $ do
        -- TODO: complex assignment: [Subscript {subscriptee = Var {var_ident = Ident {ident_string = "d", ident_annot = SpanPoint {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 24, span_column = 13}}, expr_annot = SpanPoint {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 24, span_column = 13}}, subscript_expr = Call {call_fun = Var {var_ident = Ident {ident_string = "b", ident_annot = SpanPoint {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 24, span_column = 15}}, expr_annot = SpanPoint {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 24, span_column = 15}}, call_args = [ArgExpr {arg_expr = Strings {strings_strings = ["'phases'"], expr_annot = SpanCoLinear {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 24, span_start_column = 17, span_end_column = 24}}, arg_annot = SpanCoLinear {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 24, span_start_column = 17, span_end_column = 24}}], expr_annot = SpanCoLinear {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 24, span_start_column = 15, span_end_column = 25}}, expr_annot = SpanCoLinear {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 24, span_start_column = 13, span_end_column = 26}}]
      -- TODO: client.summary `shouldBe` -- TODO: Dictionary {dict_mappings = [DictMappingPair (Call

  it "should detect dirty working directory" $
    withTestRepo $ \bt -> do
      let client = btClient bt
      commonAppendFile "a" "a"
      (rev, node) <- C.commit client ((mkDefaultCommitOptions "first") { commitAddRemove = True })
      commonAppendFile "a" "a"
      d <- -- TODO: Dictionary {dict_mappings = [DictMappingPair (Call
      when (-- TODO: self.client.version == (3, 5)) $ do
        -- TODO: complex assignment: [Subscript {subscriptee = Var {var_ident = Ident {ident_string = "d", ident_annot = SpanPoint {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 38, span_column = 13}}, expr_annot = SpanPoint {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 38, span_column = 13}}, subscript_expr = Call {call_fun = Var {var_ident = Ident {ident_string = "b", ident_annot = SpanPoint {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 38, span_column = 15}}, expr_annot = SpanPoint {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 38, span_column = 15}}, call_args = [ArgExpr {arg_expr = Strings {strings_strings = ["'phases'"], expr_annot = SpanCoLinear {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 38, span_start_column = 17, span_end_column = 24}}, arg_annot = SpanCoLinear {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 38, span_start_column = 17, span_end_column = 24}}], expr_annot = SpanCoLinear {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 38, span_start_column = 15, span_end_column = 25}}, expr_annot = SpanCoLinear {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 38, span_start_column = 13, span_end_column = 26}}]
      -- TODO: client.summary `shouldBe` -- TODO: Dictionary {dict_mappings = [DictMappingPair (Call

  it "should handle secret commit clean" $
    withTestRepo $ \bt -> do
      let client = btClient bt
      when (-- TODO: self.client.version -- TODO: LessThan {op_annot = SpanPoint {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 43, span_column = 32}} (2, 1)) $ do
        -- TODO: raise statement
      commonAppendFile "a" "a"
      (rev, node) <- C.commit client ((mkDefaultCommitOptions "first") { commitAddRemove = True })
      C.phase client ["%d" -- TODO: Modulo {op_annot = SpanPoint {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 47, span_column = 36}} rev] (C.defaultPhaseOptions { -- TODO: options secret=True force=True })
      e <- -- TODO: client.summary
      (-- TODO: client.summary !! "commit") `shouldBe` True

  it "should handle update" $
    withTestRepo $ \bt -> do
      let client = btClient bt
      commonAppendFile "a" "a"
      (rev, node) <- C.commit client ((mkDefaultCommitOptions "first") { commitAddRemove = True })
      commonAppendFile "a" "a"
      C.commit client (mkDefaultCommitOptions "second")
      C.update client 0
      d <- -- TODO: Dictionary {dict_mappings = [DictMappingPair (Call
      when (-- TODO: self.client.version == (3, 5)) $ do
        -- TODO: complex assignment: [Subscript {subscriptee = Var {var_ident = Ident {ident_string = "d", ident_annot = SpanPoint {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 63, span_column = 13}}, expr_annot = SpanPoint {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 63, span_column = 13}}, subscript_expr = Call {call_fun = Var {var_ident = Ident {ident_string = "b", ident_annot = SpanPoint {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 63, span_column = 15}}, expr_annot = SpanPoint {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 63, span_column = 15}}, call_args = [ArgExpr {arg_expr = Strings {strings_strings = ["'phases'"], expr_annot = SpanCoLinear {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 63, span_start_column = 17, span_end_column = 24}}, arg_annot = SpanCoLinear {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 63, span_start_column = 17, span_end_column = 24}}], expr_annot = SpanCoLinear {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 63, span_start_column = 15, span_end_column = 25}}, expr_annot = SpanCoLinear {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 63, span_start_column = 13, span_end_column = 26}}]
      -- TODO: client.summary `shouldBe` -- TODO: Dictionary {dict_mappings = [DictMappingPair (Call

  it "should handle remote" $
    withTestRepo $ \bt -> do
      let client = btClient bt
      commonAppendFile "a" "a"
      (rev, node) <- C.commit client ((mkDefaultCommitOptions "first") { commitAddRemove = True })
      C.clone client  (C.mkDefaultCloneOptions { -- TODO: options dest="other" })
      other <- -- TODO: hglib.open
      d <- -- TODO: Dictionary {dict_mappings = [DictMappingPair (Call
      -- TODO: other.summary `shouldBe` -- TODO: Dictionary {dict_mappings = [DictMappingPair (Call
      commonAppendFile "a" "a"
      C.commit client (mkDefaultCommitOptions "second")
      -- TODO: complex assignment: [Subscript {subscriptee = Var {var_ident = Ident {ident_string = "d", ident_annot = SpanPoint {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 85, span_column = 9}}, expr_annot = SpanPoint {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 85, span_column = 9}}, subscript_expr = Call {call_fun = Var {var_ident = Ident {ident_string = "b", ident_annot = SpanPoint {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 85, span_column = 11}}, expr_annot = SpanPoint {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 85, span_column = 11}}, call_args = [ArgExpr {arg_expr = Strings {strings_strings = ["'remote'"], expr_annot = SpanCoLinear {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 85, span_start_column = 13, span_end_column = 20}}, arg_annot = SpanCoLinear {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 85, span_start_column = 13, span_end_column = 20}}], expr_annot = SpanCoLinear {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 85, span_start_column = 11, span_end_column = 21}}, expr_annot = SpanCoLinear {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 85, span_start_column = 9, span_end_column = 22}}]
      -- TODO: other.summary `shouldBe` -- TODO: Dictionary {dict_mappings = [DictMappingPair (Call
      C.bookmark client "bm"
      -- TODO: complex assignment: [Subscript {subscriptee = Var {var_ident = Ident {ident_string = "d", ident_annot = SpanPoint {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 89, span_column = 9}}, expr_annot = SpanPoint {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 89, span_column = 9}}, subscript_expr = Call {call_fun = Var {var_ident = Ident {ident_string = "b", ident_annot = SpanPoint {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 89, span_column = 11}}, expr_annot = SpanPoint {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 89, span_column = 11}}, call_args = [ArgExpr {arg_expr = Strings {strings_strings = ["'remote'"], expr_annot = SpanCoLinear {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 89, span_start_column = 13, span_end_column = 20}}, arg_annot = SpanCoLinear {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 89, span_start_column = 13, span_end_column = 20}}], expr_annot = SpanCoLinear {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 89, span_start_column = 11, span_end_column = 21}}, expr_annot = SpanCoLinear {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 89, span_start_column = 9, span_end_column = 22}}]
      -- TODO: other.summary `shouldBe` -- TODO: Dictionary {dict_mappings = [DictMappingPair (Call
      -- TODO: other.bookmark
      -- TODO: complex assignment: [Subscript {subscriptee = Var {var_ident = Ident {ident_string = "d", ident_annot = SpanPoint {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 93, span_column = 9}}, expr_annot = SpanPoint {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 93, span_column = 9}}, subscript_expr = Call {call_fun = Var {var_ident = Ident {ident_string = "b", ident_annot = SpanPoint {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 93, span_column = 11}}, expr_annot = SpanPoint {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 93, span_column = 11}}, call_args = [ArgExpr {arg_expr = Strings {strings_strings = ["'remote'"], expr_annot = SpanCoLinear {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 93, span_start_column = 13, span_end_column = 20}}, arg_annot = SpanCoLinear {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 93, span_start_column = 13, span_end_column = 20}}], expr_annot = SpanCoLinear {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 93, span_start_column = 11, span_end_column = 21}}, expr_annot = SpanCoLinear {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 93, span_start_column = 9, span_end_column = 22}}]
      if -- TODO: self.client.version -- TODO: LessThan {op_annot = SpanPoint {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 94, span_column = 32}} (2, 0, 0)
        then do
          -- TODO: complex assignment: [Subscript {subscriptee = Var {var_ident = Ident {ident_string = "d", ident_annot = SpanPoint {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 95, span_column = 13}}, expr_annot = SpanPoint {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 95, span_column = 13}}, subscript_expr = Call {call_fun = Var {var_ident = Ident {ident_string = "b", ident_annot = SpanPoint {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 95, span_column = 15}}, expr_annot = SpanPoint {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 95, span_column = 15}}, call_args = [ArgExpr {arg_expr = Strings {strings_strings = ["'parent'"], expr_annot = SpanCoLinear {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 95, span_start_column = 17, span_end_column = 24}}, arg_annot = SpanCoLinear {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 95, span_start_column = 17, span_end_column = 24}}], expr_annot = SpanCoLinear {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 95, span_start_column = 15, span_end_column = 25}}, expr_annot = SpanCoLinear {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 95, span_start_column = 13, span_end_column = 26}}]
        else do
          -- TODO: complex assignment: [Subscript {subscriptee = Var {var_ident = Ident {ident_string = "d", ident_annot = SpanPoint {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 97, span_column = 13}}, expr_annot = SpanPoint {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 97, span_column = 13}}, subscript_expr = Call {call_fun = Var {var_ident = Ident {ident_string = "b", ident_annot = SpanPoint {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 97, span_column = 15}}, expr_annot = SpanPoint {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 97, span_column = 15}}, call_args = [ArgExpr {arg_expr = Strings {strings_strings = ["'bookmarks'"], expr_annot = SpanCoLinear {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 97, span_start_column = 17, span_end_column = 27}}, arg_annot = SpanCoLinear {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 97, span_start_column = 17, span_end_column = 27}}], expr_annot = SpanCoLinear {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 97, span_start_column = 15, span_end_column = 28}}, expr_annot = SpanCoLinear {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 97, span_start_column = 13, span_end_column = 29}}]
      -- TODO: other.summary `shouldBe` -- TODO: Dictionary {dict_mappings = [DictMappingPair (Call
      commonAppendFile "other/a" "a"
      (rev, node) <- -- TODO: other.commit
      -- TODO: complex assignment: [Subscript {subscriptee = Var {var_ident = Ident {ident_string = "d", ident_annot = SpanPoint {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 103, span_column = 9}}, expr_annot = SpanPoint {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 103, span_column = 9}}, subscript_expr = Call {call_fun = Var {var_ident = Ident {ident_string = "b", ident_annot = SpanPoint {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 103, span_column = 11}}, expr_annot = SpanPoint {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 103, span_column = 11}}, call_args = [ArgExpr {arg_expr = Strings {strings_strings = ["'remote'"], expr_annot = SpanCoLinear {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 103, span_start_column = 13, span_end_column = 20}}, arg_annot = SpanCoLinear {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 103, span_start_column = 13, span_end_column = 20}}], expr_annot = SpanCoLinear {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 103, span_start_column = 11, span_end_column = 21}}, expr_annot = SpanCoLinear {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 103, span_start_column = 9, span_end_column = 22}}]
      if -- TODO: self.client.version -- TODO: LessThan {op_annot = SpanPoint {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 104, span_column = 32}} (2, 0, 0)
        then do
          tags <- "tip bmother"
        else do
          tags <- "tip"
      -- TODO: complex assignment: [Subscript {subscriptee = Var {var_ident = Ident {ident_string = "d", ident_annot = SpanPoint {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 108, span_column = 9}}, expr_annot = SpanPoint {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 108, span_column = 9}}, subscript_expr = Call {call_fun = Var {var_ident = Ident {ident_string = "b", ident_annot = SpanPoint {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 108, span_column = 11}}, expr_annot = SpanPoint {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 108, span_column = 11}}, call_args = [ArgExpr {arg_expr = Strings {strings_strings = ["'parent'"], expr_annot = SpanCoLinear {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 108, span_start_column = 13, span_end_column = 20}}, arg_annot = SpanCoLinear {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 108, span_start_column = 13, span_end_column = 20}}], expr_annot = SpanCoLinear {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 108, span_start_column = 11, span_end_column = 21}}, expr_annot = SpanCoLinear {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 108, span_start_column = 9, span_end_column = 22}}]
      when (-- TODO: self.client.version == (3, 5)) $ do
        -- TODO: complex assignment: [Subscript {subscriptee = Var {var_ident = Ident {ident_string = "d", ident_annot = SpanPoint {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 110, span_column = 13}}, expr_annot = SpanPoint {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 110, span_column = 13}}, subscript_expr = Call {call_fun = Var {var_ident = Ident {ident_string = "b", ident_annot = SpanPoint {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 110, span_column = 15}}, expr_annot = SpanPoint {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 110, span_column = 15}}, call_args = [ArgExpr {arg_expr = Strings {strings_strings = ["'phases'"], expr_annot = SpanCoLinear {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 110, span_start_column = 17, span_end_column = 24}}, arg_annot = SpanCoLinear {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 110, span_start_column = 17, span_end_column = 24}}], expr_annot = SpanCoLinear {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 110, span_start_column = 15, span_end_column = 25}}, expr_annot = SpanCoLinear {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 110, span_start_column = 13, span_end_column = 26}}]
      -- TODO: other.summary `shouldBe` -- TODO: Dictionary {dict_mappings = [DictMappingPair (Call

  it "should handle two parents" $
    withTestRepo $ \bt -> do
      let client = btClient bt
      commonAppendFile "a" "a"
      (rev0, node) <- C.commit client ((mkDefaultCommitOptions "first") { commitAddRemove = True })
      commonAppendFile "a" "a"
      (rev1, node1) <- C.commit client (mkDefaultCommitOptions "second")
      C.update client rev0
      commonAppendFile "b" "a"
      (rev2, node2) <- C.commit client ((mkDefaultCommitOptions "third") { commitAddRemove = True })
      C.merge client rev1
      d <- -- TODO: Dictionary {dict_mappings = [DictMappingPair (Call
      when (-- TODO: self.client.version == (3, 5)) $ do
        -- TODO: complex assignment: [Subscript {subscriptee = Var {var_ident = Ident {ident_string = "d", ident_annot = SpanPoint {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 133, span_column = 13}}, expr_annot = SpanPoint {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 133, span_column = 13}}, subscript_expr = Call {call_fun = Var {var_ident = Ident {ident_string = "b", ident_annot = SpanPoint {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 133, span_column = 15}}, expr_annot = SpanPoint {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 133, span_column = 15}}, call_args = [ArgExpr {arg_expr = Strings {strings_strings = ["'phases'"], expr_annot = SpanCoLinear {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 133, span_start_column = 17, span_end_column = 24}}, arg_annot = SpanCoLinear {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 133, span_start_column = 17, span_end_column = 24}}], expr_annot = SpanCoLinear {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 133, span_start_column = 15, span_end_column = 25}}, expr_annot = SpanCoLinear {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 133, span_start_column = 13, span_end_column = 26}}]
      -- TODO: client.summary `shouldBe` -- TODO: Dictionary {dict_mappings = [DictMappingPair (Call


-- WARNINGS:
-- Unknown client method: summary
-- Unknown client method: summary
-- Unknown client method: summary
-- Unknown client method: summary
-- Unknown client method: summary
-- Unknown client method: summary
-- Unknown client method: summary
-- TODOS:
-- Unhandled expression: Dictionary {dict_mappings = [DictMappingPair (Call
-- Unhandled expression: Dictionary {dict_mappings = [DictMappingPair (Call
-- Unhandled expression: Dictionary {dict_mappings = [DictMappingPair (Call
-- Unhandled expression: Dictionary {dict_mappings = [DictMappingPair (Call
-- Unhandled method call: hglib.open
-- Unhandled expression: Dictionary {dict_mappings = [DictMappingPair (Call
-- Unhandled expression: Dictionary {dict_mappings = [DictMappingPair (Call
-- Unhandled expression: Dictionary {dict_mappings = [DictMappingPair (Call
-- Unhandled expression: Dictionary {dict_mappings = [DictMappingPair (Call
-- Unhandled module attribute: self.client.version
-- Complex assignment pattern: [Subscript {subscriptee = Var {var_ident = Ident {ident_string = "d", ident_annot = SpanPoint {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 24, span_column = 13}}, expr_annot = SpanPoint {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 24, span_column = 13}}, subscript_expr = Call {call_fun = Var {var_ident = Ident {ident_string = "b", ident_annot = SpanPoint {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 24, span_column = 15}}, expr_annot = SpanPoint {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 24, span_column = 15}}, call_args = [ArgExpr {arg_expr = Strings {strings_strings = ["'phases'"], expr_annot = SpanCoLinear {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 24, span_start_column = 17, span_end_column = 24}}, arg_annot = SpanCoLinear {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 24, span_start_column = 17, span_end_column = 24}}], expr_annot = SpanCoLinear {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 24, span_start_column = 15, span_end_column = 25}}, expr_annot = SpanCoLinear {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 24, span_start_column = 13, span_end_column = 26}}]
-- Unhandled expression: Dictionary {dict_mappings = [DictMappingPair (Call
-- Unhandled module attribute: self.client.version
-- Complex assignment pattern: [Subscript {subscriptee = Var {var_ident = Ident {ident_string = "d", ident_annot = SpanPoint {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 38, span_column = 13}}, expr_annot = SpanPoint {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 38, span_column = 13}}, subscript_expr = Call {call_fun = Var {var_ident = Ident {ident_string = "b", ident_annot = SpanPoint {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 38, span_column = 15}}, expr_annot = SpanPoint {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 38, span_column = 15}}, call_args = [ArgExpr {arg_expr = Strings {strings_strings = ["'phases'"], expr_annot = SpanCoLinear {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 38, span_start_column = 17, span_end_column = 24}}, arg_annot = SpanCoLinear {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 38, span_start_column = 17, span_end_column = 24}}], expr_annot = SpanCoLinear {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 38, span_start_column = 15, span_end_column = 25}}, expr_annot = SpanCoLinear {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 38, span_start_column = 13, span_end_column = 26}}]
-- Unhandled module attribute: self.client.version
-- Unhandled binary operator: LessThan {op_annot = SpanPoint {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 43, span_column = 32}}
-- Raise statement conversion
-- Unhandled binary operator: Modulo {op_annot = SpanPoint {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 47, span_column = 36}}
-- Unhandled expression: Dictionary {dict_mappings = [DictMappingPair (Call
-- Unhandled module attribute: self.client.version
-- Complex assignment pattern: [Subscript {subscriptee = Var {var_ident = Ident {ident_string = "d", ident_annot = SpanPoint {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 63, span_column = 13}}, expr_annot = SpanPoint {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 63, span_column = 13}}, subscript_expr = Call {call_fun = Var {var_ident = Ident {ident_string = "b", ident_annot = SpanPoint {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 63, span_column = 15}}, expr_annot = SpanPoint {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 63, span_column = 15}}, call_args = [ArgExpr {arg_expr = Strings {strings_strings = ["'phases'"], expr_annot = SpanCoLinear {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 63, span_start_column = 17, span_end_column = 24}}, arg_annot = SpanCoLinear {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 63, span_start_column = 17, span_end_column = 24}}], expr_annot = SpanCoLinear {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 63, span_start_column = 15, span_end_column = 25}}, expr_annot = SpanCoLinear {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 63, span_start_column = 13, span_end_column = 26}}]
-- Unhandled method call: hglib.open
-- Unhandled expression: Dictionary {dict_mappings = [DictMappingPair (Call
-- Unhandled method call: other.summary
-- Complex assignment pattern: [Subscript {subscriptee = Var {var_ident = Ident {ident_string = "d", ident_annot = SpanPoint {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 85, span_column = 9}}, expr_annot = SpanPoint {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 85, span_column = 9}}, subscript_expr = Call {call_fun = Var {var_ident = Ident {ident_string = "b", ident_annot = SpanPoint {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 85, span_column = 11}}, expr_annot = SpanPoint {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 85, span_column = 11}}, call_args = [ArgExpr {arg_expr = Strings {strings_strings = ["'remote'"], expr_annot = SpanCoLinear {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 85, span_start_column = 13, span_end_column = 20}}, arg_annot = SpanCoLinear {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 85, span_start_column = 13, span_end_column = 20}}], expr_annot = SpanCoLinear {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 85, span_start_column = 11, span_end_column = 21}}, expr_annot = SpanCoLinear {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 85, span_start_column = 9, span_end_column = 22}}]
-- Unhandled method call: other.summary
-- Complex assignment pattern: [Subscript {subscriptee = Var {var_ident = Ident {ident_string = "d", ident_annot = SpanPoint {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 89, span_column = 9}}, expr_annot = SpanPoint {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 89, span_column = 9}}, subscript_expr = Call {call_fun = Var {var_ident = Ident {ident_string = "b", ident_annot = SpanPoint {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 89, span_column = 11}}, expr_annot = SpanPoint {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 89, span_column = 11}}, call_args = [ArgExpr {arg_expr = Strings {strings_strings = ["'remote'"], expr_annot = SpanCoLinear {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 89, span_start_column = 13, span_end_column = 20}}, arg_annot = SpanCoLinear {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 89, span_start_column = 13, span_end_column = 20}}], expr_annot = SpanCoLinear {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 89, span_start_column = 11, span_end_column = 21}}, expr_annot = SpanCoLinear {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 89, span_start_column = 9, span_end_column = 22}}]
-- Unhandled method call: other.summary
-- Unhandled method call: other.bookmark
-- Complex assignment pattern: [Subscript {subscriptee = Var {var_ident = Ident {ident_string = "d", ident_annot = SpanPoint {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 93, span_column = 9}}, expr_annot = SpanPoint {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 93, span_column = 9}}, subscript_expr = Call {call_fun = Var {var_ident = Ident {ident_string = "b", ident_annot = SpanPoint {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 93, span_column = 11}}, expr_annot = SpanPoint {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 93, span_column = 11}}, call_args = [ArgExpr {arg_expr = Strings {strings_strings = ["'remote'"], expr_annot = SpanCoLinear {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 93, span_start_column = 13, span_end_column = 20}}, arg_annot = SpanCoLinear {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 93, span_start_column = 13, span_end_column = 20}}], expr_annot = SpanCoLinear {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 93, span_start_column = 11, span_end_column = 21}}, expr_annot = SpanCoLinear {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 93, span_start_column = 9, span_end_column = 22}}]
-- Unhandled module attribute: self.client.version
-- Unhandled binary operator: LessThan {op_annot = SpanPoint {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 94, span_column = 32}}
-- Complex assignment pattern: [Subscript {subscriptee = Var {var_ident = Ident {ident_string = "d", ident_annot = SpanPoint {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 95, span_column = 13}}, expr_annot = SpanPoint {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 95, span_column = 13}}, subscript_expr = Call {call_fun = Var {var_ident = Ident {ident_string = "b", ident_annot = SpanPoint {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 95, span_column = 15}}, expr_annot = SpanPoint {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 95, span_column = 15}}, call_args = [ArgExpr {arg_expr = Strings {strings_strings = ["'parent'"], expr_annot = SpanCoLinear {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 95, span_start_column = 17, span_end_column = 24}}, arg_annot = SpanCoLinear {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 95, span_start_column = 17, span_end_column = 24}}], expr_annot = SpanCoLinear {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 95, span_start_column = 15, span_end_column = 25}}, expr_annot = SpanCoLinear {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 95, span_start_column = 13, span_end_column = 26}}]
-- Complex assignment pattern: [Subscript {subscriptee = Var {var_ident = Ident {ident_string = "d", ident_annot = SpanPoint {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 97, span_column = 13}}, expr_annot = SpanPoint {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 97, span_column = 13}}, subscript_expr = Call {call_fun = Var {var_ident = Ident {ident_string = "b", ident_annot = SpanPoint {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 97, span_column = 15}}, expr_annot = SpanPoint {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 97, span_column = 15}}, call_args = [ArgExpr {arg_expr = Strings {strings_strings = ["'bookmarks'"], expr_annot = SpanCoLinear {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 97, span_start_column = 17, span_end_column = 27}}, arg_annot = SpanCoLinear {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 97, span_start_column = 17, span_end_column = 27}}], expr_annot = SpanCoLinear {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 97, span_start_column = 15, span_end_column = 28}}, expr_annot = SpanCoLinear {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 97, span_start_column = 13, span_end_column = 29}}]
-- Unhandled method call: other.summary
-- Unhandled method call: other.commit
-- Complex assignment pattern: [Subscript {subscriptee = Var {var_ident = Ident {ident_string = "d", ident_annot = SpanPoint {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 103, span_column = 9}}, expr_annot = SpanPoint {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 103, span_column = 9}}, subscript_expr = Call {call_fun = Var {var_ident = Ident {ident_string = "b", ident_annot = SpanPoint {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 103, span_column = 11}}, expr_annot = SpanPoint {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 103, span_column = 11}}, call_args = [ArgExpr {arg_expr = Strings {strings_strings = ["'remote'"], expr_annot = SpanCoLinear {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 103, span_start_column = 13, span_end_column = 20}}, arg_annot = SpanCoLinear {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 103, span_start_column = 13, span_end_column = 20}}], expr_annot = SpanCoLinear {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 103, span_start_column = 11, span_end_column = 21}}, expr_annot = SpanCoLinear {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 103, span_start_column = 9, span_end_column = 22}}]
-- Unhandled module attribute: self.client.version
-- Unhandled binary operator: LessThan {op_annot = SpanPoint {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 104, span_column = 32}}
-- Complex assignment pattern: [Subscript {subscriptee = Var {var_ident = Ident {ident_string = "d", ident_annot = SpanPoint {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 108, span_column = 9}}, expr_annot = SpanPoint {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 108, span_column = 9}}, subscript_expr = Call {call_fun = Var {var_ident = Ident {ident_string = "b", ident_annot = SpanPoint {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 108, span_column = 11}}, expr_annot = SpanPoint {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 108, span_column = 11}}, call_args = [ArgExpr {arg_expr = Strings {strings_strings = ["'parent'"], expr_annot = SpanCoLinear {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 108, span_start_column = 13, span_end_column = 20}}, arg_annot = SpanCoLinear {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 108, span_start_column = 13, span_end_column = 20}}], expr_annot = SpanCoLinear {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 108, span_start_column = 11, span_end_column = 21}}, expr_annot = SpanCoLinear {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 108, span_start_column = 9, span_end_column = 22}}]
-- Unhandled module attribute: self.client.version
-- Complex assignment pattern: [Subscript {subscriptee = Var {var_ident = Ident {ident_string = "d", ident_annot = SpanPoint {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 110, span_column = 13}}, expr_annot = SpanPoint {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 110, span_column = 13}}, subscript_expr = Call {call_fun = Var {var_ident = Ident {ident_string = "b", ident_annot = SpanPoint {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 110, span_column = 15}}, expr_annot = SpanPoint {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 110, span_column = 15}}, call_args = [ArgExpr {arg_expr = Strings {strings_strings = ["'phases'"], expr_annot = SpanCoLinear {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 110, span_start_column = 17, span_end_column = 24}}, arg_annot = SpanCoLinear {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 110, span_start_column = 17, span_end_column = 24}}], expr_annot = SpanCoLinear {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 110, span_start_column = 15, span_end_column = 25}}, expr_annot = SpanCoLinear {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 110, span_start_column = 13, span_end_column = 26}}]
-- Unhandled method call: other.summary
-- Unhandled expression: Dictionary {dict_mappings = [DictMappingPair (Call
-- Unhandled module attribute: self.client.version
-- Complex assignment pattern: [Subscript {subscriptee = Var {var_ident = Ident {ident_string = "d", ident_annot = SpanPoint {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 133, span_column = 13}}, expr_annot = SpanPoint {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 133, span_column = 13}}, subscript_expr = Call {call_fun = Var {var_ident = Ident {ident_string = "b", ident_annot = SpanPoint {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 133, span_column = 15}}, expr_annot = SpanPoint {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 133, span_column = 15}}, call_args = [ArgExpr {arg_expr = Strings {strings_strings = ["'phases'"], expr_annot = SpanCoLinear {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 133, span_start_column = 17, span_end_column = 24}}, arg_annot = SpanCoLinear {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 133, span_start_column = 17, span_end_column = 24}}], expr_annot = SpanCoLinear {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 133, span_start_column = 15, span_end_column = 25}}, expr_annot = SpanCoLinear {span_filename = "/workspaces/ghc/tmp/python-hglib/tests/test_summary.py", span_row = 133, span_start_column = 13, span_end_column = 26}}]
