name:                haskell-hglib
version:             0.1.0.0
github:              "aanno/haskell-hglib"
license:             BSD-3-Clause
author:              "aanno"
maintainer:          "aanno@users.noreply.github.com"
copyright:           "2025 Thomas Pasch"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README.md on GitHub at <https://github.com/aanno/haskell-hglib>

dependencies:
- base >= 4.7 && < 5
- process >= 1.6.25.0
- time >= 1.12.2
- text >= 2.1.1
- bytestring >= 0.12.1.0
- aeson >= 2.2.3.0
- binary >= 0.8.9.1
- optparse-applicative
- vector >= 0.13.2.0
- scientific >= 0.3.8.0
- unordered-containers >= 0.2.20
# logging
- filepath >= 1.4.301.0
- stm >= 2.5.3.1
- async
- tasty >= 1.5.3
- streamly >= 0.10.1
- streamly-core >= 0.2.3
# state monad
- mtl >= 2.2.2
- containers >= 0.6.7

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints
# - -O2
# - -fprint-potential-instances
# silence a bit for development
- -Wno-unused-matches
- -Wno-unused-imports
- -Wno-unused-top-binds
- -Wno-unused-local-binds
- -Wno-orphans
- -Wno-partial-fields
- -Wno-unused-do-bind

library:
  source-dirs: src

executables:
  haskell-hglib-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-hglib
    - async
    - aeson
    - streamly >= 0.10.1
    - streamly-core >= 0.2.3
    # NOT used here - but needed because of an stack bug
    # - language-python >= 0.6.0
  python-testcase-converter-exe:
    main:                PythonTestcaseConverter.hs
    source-dirs:         converter
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-hglib
    - language-python >= 0.6.0
    # - language-python >= 0.5.8
  #!/bin/sh
exedir="/stratis/home/tpasch/dev/.stack/programs/x86_64-linux/ghc-tinfo6-9.6.6/lib/ghc-9.6.6/bin"
exeprog="./ghc-9.6.6"
executablename="/stratis/home/tpasch/dev/.stack/programs/x86_64-linux/ghc-tinfo6-9.6.6/lib/ghc-9.6.6/bin/./ghc-9.6.6"
bindir="/stratis/home/tpasch/dev/.stack/programs/x86_64-linux/ghc-tinfo6-9.6.6/bin"
libdir="/stratis/home/tpasch/dev/.stack/programs/x86_64-linux/ghc-tinfo6-9.6.6/lib/ghc-9.6.6/lib"
docdir="/stratis/home/tpasch/dev/.stack/programs/x86_64-linux/ghc-tinfo6-9.6.6/share/doc/ghc-9.6.6"
includedir="/stratis/home/tpasch/dev/.stack/programs/x86_64-linux/ghc-tinfo6-9.6.6/include"

exec "$executablename" -B"$libdir" ${1+"$@"}:
    main:                Main.hs
    source-dirs:         converter
    other-modules:
    - ConverterState
    - StatefulConverter
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-hglib
    - language-python >= 0.6.0
    - mtl >= 2.2.2
    - containers >= 0.6.7

tests:
  haskell-hglib-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-hglib
    - hspec-core >= 2.11.12
    - hspec >= 2.11.12
    - temporary
    - directory
    - process
    - time
    # NOT used here - but needed because of an stack bug
    # - language-python >= 0.6.0
